/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as FlavoursRouteImport } from './routes/flavours'
import { Route as MixlabRouteImport } from './routes/mixlab'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavoursRoute = FlavoursRouteImport.update({
  id: '/flavours',
  path: '/flavours',
  getParentRoute: () => rootRouteImport,
} as any)
const MixlabRoute = MixlabRouteImport.update({
  id: '/mixlab',
  path: '/mixlab',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/flavours': typeof FlavoursRoute
  '/mixlab': typeof MixlabRoute
  '/upload': typeof UploadRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/flavours': typeof FlavoursRoute
  '/mixlab': typeof MixlabRoute
  '/upload': typeof UploadRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/flavours': typeof FlavoursRoute
  '/mixlab': typeof MixlabRoute
  '/upload': typeof UploadRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buy' | '/flavours' | '/mixlab' | '/upload' | '/admin/dashboard' | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buy' | '/flavours' | '/mixlab' | '/upload' | '/admin/dashboard' | '/admin/login'
  id: '__root__' | '/' | '/buy' | '/flavours' | '/mixlab' | '/upload' | '/admin/dashboard' | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyRoute: typeof BuyRoute
  FlavoursRoute: typeof FlavoursRoute
  MixlabRoute: typeof MixlabRoute
  UploadRoute: typeof UploadRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavours': {
      id: '/flavours'
      path: '/flavours'
      fullPath: '/flavours'
      preLoaderRoute: typeof FlavoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mixlab': {
      id: '/mixlab'
      path: '/mixlab'
      fullPath: '/mixlab'
      preLoaderRoute: typeof MixlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyRoute: BuyRoute,
  FlavoursRoute: FlavoursRoute,
  MixlabRoute: MixlabRoute,
  UploadRoute: UploadRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
